apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator
spec:
  selector:
    app: citus-coordinator
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-coordinator
spec:
  replicas: 1
  selector:
    matchLabels: { app: citus-coordinator }
  template:
    metadata:
      labels: { app: citus-coordinator }
    spec:
      containers:
      - name: citus-coordinator
        image: citusdata/citus:postgres_16
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - containerPort: 5432
        args: ["-c","shared_preload_libraries=citus"]
